---
collections:
  - name: awx.awx
  - name: azure.azcollection
  - name: amazon.aws
  - name: git+https://github.com/test-rt-bl/community.vmware.git
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: ansible.utils
  - name: ansible.netcommon
  - name: chocolatey.chocolatey
  - name: community.windows
  - name: community.crypto
  - name: community.general
  - name: community.aws
  - name: community.azure
  - name: community.docker
  - name: community.grafana
  - name: community.hashi_vault
  - name: community.kubernetes
  - name: community.network
  - name: servicenow.servicenow
